apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-imsvibog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-imsvibog 
  name: go-imsvibog
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-imsvibog
    weight: 100 
